config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"

  mount ActionCable.server => '/cable'

  resources :resources
  resources :services
  post '/services/:id', to: 'services#create'
  patch '/services/:id', to: 'services#update'
  post '/services/:id/deploy', to: 'services#deploy', as: "deploy_service"
  post '/services/deploy', to: 'services#deploy_all'
  get '/services/:name/status', to: 'services#status'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resource.rb
class Resource < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :docker_image, presence: true

  has_many :services, dependent: :destroy

end

app/models/s.rb
res

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :resource
  validates :name, presence: true, uniqueness: true

  def device_configuration?
    self.max_gpu || self.min_gpu || self.max_memory || self.min_memory
  end

  def deploy_data
    deploy_data = {}
    deploy_data["name"] = self.name
    deploy_data["image"] = self.resource.docker_image
    deploy_data["version"] = "latest"
    if device_configuration?
      deploy_data["device_configuration"] = {}
      deploy_data["device_configuration"]["memory"] = self.min_memory.to_i.to_s+"Mi" if self.min_memory
      deploy_data["device_configuration"]["memory_limit"] = self.max_memory.to_i.to_s+"Mi" if self.max_memory
      deploy_data["device_configuration"]["cpu"] = self.min_gpu.to_i.to_s+"m" if self.min_gpu
      deploy_data["device_configuration"]["cpu_limit"] = self.max_gpu.to_i.to_s+"m" if self.max_gpu
    end
    deploy_data["properties"] = {}
    deploy_data["properties"]["port"] = self.resource.internal_port


    deploy_data
  end
end

#
#
# "name": "treem",
# "image": "jpmml/openscoring",
# "version": "latest",
# "device_configuration": {
#   "memory":"5Mi",
#   "memory_limit":"5Mi",
#   "cpu":"100m",
#   "cpu_limit":"200m"
# }

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login

  def index
    @resources = Resource.all
    @services = Service.all
    @resource = Resource.new()

  end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :require_login


  def create
    @resource = Resource.new(resource_params)
    @resource.save
    @resources = Resource.all
    respond_to do |f|
      f.js
    end
  end

  def destroy
    @resource = Resource.find(params[:id])
    @resource.destroy
    @resources = Resource.all
    respond_to do |f|
      f.js
    end
  end

  private
    def resource_params
      params.require(:resource).permit(:name, :docker_image, :resource_type, :description, :internal_port)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :require_login


  def create
    resource = Resource.where(id: params[:id]).first
    @service = Service.new
    if resource
      @service = resource.services.create(name: resource.name.downcase+"-#{rand(0...999)}", resource_id: resource.id, topic: resource.name, status: "pending")
      @service.save
    end

    @services = Service.all
    respond_to do |f|
      f.js
    end
  end

  def show
    @service = Service.find(params[:id])
    @services = Service.all
    respond_to do |f|
      f.js
    end
  end

  def update
    if @service = Service.find(params[:id])
      @service.update(service_params)
    end
    @services = Service.all
    respond_to do |f|
      f.js
    end

  end

  def destroy
    if @service = Service.find(params[:id])
      @service.destroy
    end
    @services = Service.all
    respond_to do |f|
      f.js
    end
  end

  def status
    @services = Service.all
    val = ArietaApi.new.service_status(params[:name])
    respond_to do |f|
      f.html { render :inline => val.body }
    end
  end

  def deploy
    if @service = Service.find(params[:id])
      File.write("/tmp/service_deploy.json", [ @service.deploy_data ].to_json )
      api = ArietaApi.new
      api.deploy("/tmp/service_deploy.json")
    end
    @services = Service.all
    respond_to do |f|
      f.js
    end
  end





  private
    def service_params
      params.require(:service).permit(:id,:max_gpu,:min_gpu,:max_memory,:min_memory,:position_x,:position_y,:pmml_data_path,:input_data,:input_data_path,:outpu_data_path,:in_connection,:out_connection,:service_ip,:service_port,:service_full_path,:status,:connection_settings )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_new_resource.html.erb
<%= form_with model: @resource, id: "new_resource_form" do |form| %>

   <div id="new_resoruce_error_explanation">
   </div>

  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name,  class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description,  class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :resource_type %><br>
    <%= form.select :resource_type, options_for_select([ "store", "analytic", "misc" ], "Store") , {}, { :class => 'form-control' }%>
  </div>


  <div class="form-group">
    <%= form.label :docker_image %><br>
    <%= form.text_field :docker_image, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :internal_port %><br>
    <%= form.text_field :internal_port, class: "form-control"  %>
  </div>

  <p>
    <%= form.submit "Create", class: "btn btn-primary", style: "float:right;" %>
  </p>
<% end %>


<!-- 134911 -->

app/views/home/_resources.html.erb
<ul class="list-group" style="height: 530px; overflow-y: auto;">
  <% @resources.each do |resource|%>
    <li class="list-group-item">
      <div data-toggle="tooltip" title="image: <%= resource.docker_image %>">
        <%= resource.name %>
      </div>

      <%= link_to image_tag("cloud-upload.svg"), service_path(resource), remote: true, method: :post, title: "mark for deploy" %>

      <%= link_to image_tag("trashcan.svg"), resource_path(resource), remote: true, method: :delete, data: { confirm: 'Are you sure?' }, title: "delete resource" %> </li>
  <% end %>
</ul>

app/views/home/_services.html.erb
<% @services.each do |service|%>
  <% style = "card-body "+ service.status %>
  <% position = "width: 15rem;" %>
  <% position += " position: absolute;" if service.position_x || service.position_y%>
  <% position += " left: #{service.position_x.to_i}px;" if service.position_x%>
  <% position += " top: #{service.position_y.to_i - 183 +54}px;" if service.position_y%>
  <div class="card draggable  <%= style %>" style="<%=position%>" serviceId="<%= service.id%>" toService="<%=service.out_connection%>" id="draggable-element-<%= service.id%>">
    <h6 class="card-header  <%= style %>" >
      <%= image_tag((service.resource.resource_type)+".png", class: "small-img ")%>
      <%= service.name %>
    </h6>
    <div class="card-body">
      <p class="card-text">
        <%= service.resource.docker_image %>
      </p>
      <%= link_to image_tag("gear.svg"), service, remote: true, method: :get, title: "configure", 'data-target' =>  "#serviceSettings", 'data-toggle' => "modal" %>
      <%= link_to image_tag("rocket-green.svg"), deploy_service_path(service), remote: true, method: :post, title: "individual deploy" %>
      <%= link_to image_tag("trashcan-red.svg"), service, remote: true, method: :delete, title: "delete" %>
      <%= link_to image_tag("cloud-download-red.svg"), "#", remote: true, method: :post, title: "undeploy" %>
    </div>
  </div>

<% end %>

app/views/home/index.html.erb
<br />
<h2>Deployment View </h2>
<br />
<div id="notifications_id" style="display: none;" ></div>

<div class="container" style="margin: 0; margin-right: 0; max-width: 100%">
  <div class="row">
    <div class="col-2" >
      <div id="home_resources_display" style="border-style: solid;border-radius: 7px;">
          <%= render :file => 'home/_resources' %>
      </div>
      <br />
      <button class="btn btn-outline-primary btn-block" data-toggle="modal" data-target="#newResource">New resource</button>
    </div>
    <div class="col-10" style="padding-left: 0;">
      <div style="border-style: dashed; border-radius: 5px; height: 100%; overflow: auto;" id="services-widget">
        <%= render :file => 'home/_services' %>
        <div class="deploy-buttons">
          <button type="button" class="btn btn-outline-success">Deploy all</button>
          <button type="button" class="btn btn-outline-danger">Undeploy all</button>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <br />
      <div id="messages" class="console-view" />
    </div>
  </div>
</div>




<div class="modal fade" id="newResource" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header alert-primary" style="border-top-right-radius: 2px; border-top-left-radius: 2px;">
        <h5 class="modal-title" id="exampleModalLabel">New resource</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="close_resource_button">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render :file => 'home/_new_resource' %>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="serviceSettings" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header alert-primary"  style="border-top-right-radius: 2px; border-top-left-radius: 2px;>
        <h5 class="modal-title" id="serviceSettingTitle">Service settings</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="close_service_button">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="serviceSettingBody">
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebApp</title>
    <%= csrf_meta_tags %>

    <%= action_cable_meta_tag %>

    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous">
    </script>

    <script
      src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
      integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
      crossorigin="anonymous">
    </script>

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
      integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
      crossorigin="anonymous">
    </script>

    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
      integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
      crossorigin="anonymous">
    </script>

    <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
    integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
    crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <% if signed_in? %>
    <nav class="navbar fixed-top navbar-light bg-light">
      <a class="navbar-brand" href="#">Arieta</a>
      <span class="navbar-text">
        <button class="btn btn-outline-success" type="button">Log out</button>
      </span>
    </nav>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resources/_errors.html.erb
<h2>
  <%= pluralize(@resource.errors.count, "error") %> prohibited
  this article from being saved:
</h2>
<ul>
  <% @resource.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

app/views/resources/create.js.erb
<% if  @resource.errors.any? %>
  $('#new_resoruce_error_explanation').empty();
  $('#new_resoruce_error_explanation').append("<%= escape_javascript render(:partial => 'resources/errors', :locals => { :resource => @resource }) %>");
<% else %>
  $('#close_resource_button').click();
  $('#new_resoruce_error_explanation').empty();
  $('#new_resource_form').find("input[type=text], textarea").val("");
  $('#home_resources_display').empty();
  $("#home_resources_display").append("<%= escape_javascript render(:partial => 'home/resources', :locals => { :resources => @resources }) %>");
  $("#notifications_id").empty();
  $("#notifications_id").append('<div class="alert alert-success" role="alert">Successfully done!</div>');
  $("#notifications_id").fadeIn(3000).delay(5000).fadeOut('slow');
<% end%>

app/views/resources/destroy.js.erb
<% if  @resource.errors.any? %>
  $("#notifications_id").empty();
  $("#notifications_id").append("<div class="alert alert-warning" role="alert">This resource cant be destroy, delete all deployed resources related with this one.</div>");
<% else %>
  $('#home_resources_display').empty();
  $("#home_resources_display").append("<%= escape_javascript render(:partial => 'home/resources', :locals => { :resources => @resources }) %>");
<% end%>

app/views/services/_configuration.html.erb
<%= form_with model: @service do |form| %>

   <div id="service_error_explanation">
   </div>

  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= form.label "max GPU  (m)" %><br>
        <%= form.text_field :max_gpu,  class: "form-control"%>
      </div>
    </div>
    <div class="col">
      <div class="form-group">
        <%= form.label "min GPU  (m)" %><br>
        <%= form.text_field :min_gpu,  class: "form-control"%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="form-group">
        <%= form.label "max memory (Mi)" %><br>
        <%= form.text_field :min_memory,  class: "form-control"%>
      </div>
    </div>
    <div class="col">

      <div class="form-group">
        <%= form.label "min memory (Mi)" %><br>
        <%= form.text_field :max_memory,  class: "form-control"%>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :pmml_data_path %><br>
    <%= form.text_field :pmml_data_path,  class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :input_data_path %><br>
    <%= form.text_field :input_data_path,  class: "form-control"%>
  </div>
  
  <div class="form-group">
    <%= form.label :outpu_data_path %><br>
    <%= form.text_field :outpu_data_path,  class: "form-control"%>
  </div>


  <div class="form-group">
    <%= form.label :out_connection %><br>
    <%= form.select :out_connection, @services.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }, { :class => 'form-control' }%>
  </div>

  <div class="form-group">
    <%= form.label :connection_settings %><br>
    <%= form.text_field :connection_settings,  class: "form-control"%>
  </div>

  <p>
    <%= form.submit "Save", class: "btn btn-primary", style: "float:right;" %>
  </p>
<% end %>

app/views/services/create.js.erb
<% if  @service.errors.any? %>
  $('#new_resoruce_error_explanation').empty();
  $('#new_resoruce_error_explanation').append("<%= escape_javascript render(:partial => 'resources/errors', :locals => { :resource => @service }) %>");
<% else %>
  $('#new_resoruce_error_explanation').empty();
  $('[id^="draggable-element-"]').remove();
  $("#services-widget").append("<%= escape_javascript render(:partial => 'home/services', :locals => { :services => @services }) %>");
  $("#notifications_id").empty();
  $("#notifications_id").append('<div class="alert alert-success" role="alert">Successfully done!</div>');
  $("#notifications_id").fadeIn(3000).delay(5000).fadeOut('slow');


  makeDraggable();
<% end%>

app/views/services/deploy.js.erb
var interval= setInterval(function(){ getStatus(); }, 1000);
updateStatus("deploying");

function updateStatus(status){
  $.ajax({
    method: "PATCH",
    url: "/services/<%= @service.id%>",
    data: { service: { status: status } },

    success: function(data){
      var element = $("#draggable-element-<%=@service.id%>")
      element.removeClass("pending").removeClass("deploying").removeClass("deployed").addClass(status);
      element.find("h6").removeClass("pending").removeClass("deploying").removeClass("deployed").addClass(status);
    }
  });
}

function getStatus(){
  $.ajax({
    method: "GET",
    url: "/services/<%= @service.name%>/status",
    success: function(data){
      if(data.indexOf("Err") != -1){
        updateStatus("error");
        clearInterval(interval);
      }
      else if(data.indexOf("Runn") != -1){
        updateStatus("deployed");
        clearInterval(interval);
      }
    },
    error: function(data){
      clearInterval(interval);
    }
  });
}

app/views/services/destroy.js.erb
$('[id^="draggable-element-"]').remove();
$("#services-widget").append("<%= escape_javascript render(:partial => 'home/services', :locals => { :services => @services }) %>");

makeDraggable();

app/views/services/show.js.erb
$('#serviceSettingBody').empty();
$('#serviceSettingBody').append("<%= escape_javascript render(:partial => 'services/configuration', :locals => { :service => @service }) %>");

app/views/services/update.js.erb
<% if  @service.errors.any? %>
  $('#service_error_explanation').empty();
  $('#service_error_explanation').append("<%= escape_javascript render(:partial => 'resources/errors', :locals => { :resource => @service }) %>");
<% else %>
  $('#close_service_button').click();
  $('#service_error_explanation').empty();

<% end%>

makeDraggable();

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up login">
  <h2 style="padding-top:20%;"><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>